Added feature 02
[aarti@ps8745 trial]$ git config --global user.name "Aarti"
[aarti@ps8745 trial]$  git config --global user.email aarti_ranade@persistent.com
[aarti@ps8745 trial]$ vi ~/.gitconfig
[aarti@ps8745 trial]$ git commit -m "Added feature 01"                          # On branch featuer_01
nothing to commit (working directory clean)
[aarti@ps8745 trial]$ git status
nothing to commit (working directory clean)
[aarti@ps8745 trial]$ git push origin featuer_01
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 294 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@github.com:rtranade/trial.git
 * [new branch]      featuer_01 -> featuer_01
[aarti@ps8745 trial]$ git checkout master
Switched to branch 'master'
[aarti@ps8745 trial]$ git branch
  featuer_01
* master
[aarti@ps8745 trial]$ vi README.md
[aarti@ps8745 trial]$ git pull origin master
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From github.com:rtranade/trial
 * branch            master     -> FETCH_HEAD
Updating 0bdb88d..8a1e9ed
Fast-forward
 README.md |    2 ++
 1 files changed, 2 insertions(+), 0 deletions(-)
[aarti@ps8745 trial]$ vi README.md
[aarti@ps8745 trial]$ git branch feature_02
[aarti@ps8745 trial]$ git branch
  featuer_01
  feature_02
* master
[aarti@ps8745 trial]$
[aarti@ps8745 trial]$ git checkout feature_02
Switched to branch 'feature_02'
[aarti@ps8745 trial]$ vi feature02.txt
[aarti@ps8745 trial]$ git status
nothing added to commit but untracked files present (use "git add" to track)
[aarti@ps8745 trial]$ git add feature02.txt
[aarti@ps8745 trial]$ git commit -m "Added feature 02"
[feature_02 2130d01] Added feature 02
 1 files changed, 1 insertions(+), 0 deletions(-)
 create mode 100644 feature02.txt
[aarti@ps8745 trial]$ git push origin feature_02
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 301 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@github.com:rtranade/trial.git
 * [new branch]      feature_02 -> feature_02
[aarti@ps8745 trial]$ git checkout feature_01
error: pathspec 'feature_01' did not match any file(s) known to git.
[aarti@ps8745 trial]$ git checkout featuer_01
Switched to branch 'featuer_01'
[aarti@ps8745 trial]$ git status
nothing to commit (working directory clean)
[aarti@ps8745 trial]$ git pull origin featore_02
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
fatal: Couldn't find remote ref featore_02
[aarti@ps8745 trial]$ git pull origin feature_02
From github.com:rtranade/trial
 * branch            feature_02 -> FETCH_HEAD
Updating 25a0a13..2130d01
Fast-forward
 feature02.txt |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)
 create mode 100644 feature02.txt
[aarti@ps8745 trial]$ ll
total 8
-rw-rw-r--. 1 aarti aarti 19 Dec  8 21:20 feature02.txt
-rw-rw-r--. 1 aarti aarti 55 Dec  8 21:15 README.md
[aarti@ps8745 trial]$
      feature02.txt
[aarti@ps8745 trial]$
      feature02.txt
[aarti@ps8745 tri

 for your changes. Lines starting